version: '3.9'
name: 'docker-web-dev-environment'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ~/your/path:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: './docker/php-fpm'
    volumes:
      - ~/your/path:/var/www/html
